# 数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pro_sys
    username: root
    password: "jiajiajia1."
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    cors:
      # 允许的来源
      allowed-origins: http://18080.com
      # 设置为true以允许凭据
      allow-credentials: true





#mapper.xml配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  global-config:
    db-config:
      table-prefix: sys_
  #      id-type: auto

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 18080





